"""Expand `<!-- evidence-strip -->` into the home page's evidence strip.

The strip shows a handful of counted measures -- modules, lines of Agda,
postulates, third-party requests -- and ADR-009's third principle is the
constraint that shapes this file: every number on screen is one a script
produced.  The numbers live in `docs/assets/evidence.json`, which is committed
and regenerated deliberately (`make evidence`); this hook only renders what is
there, so the build needs no checkout and no network, and a stale number is at
least a *recorded* stale number, with the commit it was counted from shipped
alongside.

## Why a hook and not inline HTML

The same reasoning as `recent_posts_hook.py`: the strip appears on one page
today, but the markup carries the data (`data-n` for the count-up, `title`
for the producing command), and hand-maintaining that in `index.md` is how a
displayed number and its recorded command drift apart.  One renderer, one
data file, no divergence.

## The final numbers ship in the HTML

`evidence.js` animates the count-up, but the markup this hook emits already
contains each measure at its final value.  A crawler, a reader with JS off,
and a reduced-motion reader all get the real numbers with nothing missing --
the animation is a way of *arriving* at the truth, never the only carrier of
it (ADR-009).
"""

from __future__ import annotations

import json
from pathlib import Path

from mkdocs.exceptions import PluginError
from mkdocs.plugins import event_priority
from mkdocs.utils import get_relative_url

MARKER = "<!-- evidence-strip -->"

#: Relative to docs_dir.  Committed, and regenerated by `make evidence`.
DATA = "assets/evidence.json"


def _load(config):
    path = Path(config["docs_dir"]) / DATA
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise PluginError(f"{MARKER} needs {DATA}; run `make evidence`.")
    for key in ("source", "measures"):
        if key not in data:
            raise PluginError(f"{DATA} has no `{key}`; regenerate it.")
    return data


def _href(raw, page, files):
    """External URLs pass through; internal targets are source paths.

    A source path is resolved against the files collection so that a measure
    pointing at a page that has moved fails the build rather than shipping a
    dead link -- the same property `--strict` gives markdown links, done by
    hand because this hook emits HTML.
    """
    if raw.startswith(("http://", "https://")):
        return raw
    src, _, fragment = raw.partition("#")
    file = files.get_file_from_path(src)
    if file is None:
        raise PluginError(f"{DATA}: `{raw}` does not name a page in the build.")
    url = get_relative_url(file.url, page.file.url)
    return f"{url}#{fragment}" if fragment else url


def _render(data, page, files):
    cells = []
    for m in data["measures"]:
        classes = "ev-n ev-zero" if m.get("emphasis") and m["value"] == 0 else "ev-n"
        cells.append(
            f'<a class="ev" href="{_href(m["href"], page, files)}" '
            f'title="{m["command"]}">'
            f'<span class="{classes}" data-n="{m["value"]}">{m["value"]:,}</span>'
            f'<span class="ev-l">{m["label"]}</span>'
            f'<span class="ev-d">{m["detail"]}</span>'
            f"</a>"
        )
    src = data["source"]
    commit = src["commit"][:7]
    caption = (
        f'<p class="ev-caption">Counted, not asserted: the library figures are '
        f'from <a href="{src["repo"]}">ualib/agda-algebras</a> at '
        f'<code>{commit}</code> ({src["commit_date"]}), the request count from '
        f"this site's own audit.  Hover a figure for the command that produced "
        f"it; <code>make evidence</code> recounts.</p>"
    )
    return '<div class="evidence">' + "".join(cells) + "</div>\n" + caption


@event_priority(-100)
def on_page_markdown(markdown, *, page, config, files):
    if MARKER not in markdown:
        return None
    return markdown.replace(MARKER, _render(_load(config), page, files))
