"""Expand `<!-- proof-terminal -->` into the typed-proof terminal (M3-2d).

The terminal replays the hole-filling session recorded in
`docs/assets/proof.json` (regenerated by `make proof`, which drives a real
Agda over `agda/Free.lagda.md`).  This hook renders the session's *final*
state -- every line coloured, the goal count at zero, the `✓` line with the
version Agda reported -- so a crawler, a JS-off reader and a reduced-motion
reader all see the completed proof with nothing missing.  `proof.js` only
rewinds that state and types it back in (ADR-009: the animation is a way of
arriving at the truth, never the only carrier of it).

## One renderer

Same reasoning as `evidence_hook.py`: the markup carries the session data
(the hole line and the goal live in it, for the replay), and hand-writing
that into a page is how a displayed goal and a recorded one drift apart.
The JSON holds facts only; the colouring below is presentation, and it
follows `overrides/404.html`'s precedent -- Pygments' Agda vocabulary (`nf`
for a defined name, `ow` for an operator word, `c1` for a comment), so the
terminal is coloured with the same classes, off the same tokens, as every
real code block on the site.  Only identifiers the transcript lists in
`names` are coloured as definitions: the renderer never guesses at what is
a name.

## The replay's contract with this markup

`proof.js` finds, inside `.proof`: `.proof-line` elements in session order,
of which one is the hidden `.proof-hole-line` (the hole state of the line
that gets filled) and its successor `.proof-fill-line` (the final state);
`.proof-check`, revealed last, not typed -- the compiler speaks, the visitor
does not type its output; `.proof-hud`, whose `data-goal` is the recorded
goal and whose resting text is the all-done state; `.proof-goals`, the goal
pill, with the open count in the root's `data-goals-open`; and
`.proof-replay`, shipped `hidden` because a control that does nothing (JS
off) or would replay motion (reduced motion) should not exist.
"""

from __future__ import annotations

import json
import re
from html import escape
from pathlib import Path

from mkdocs.exceptions import PluginError
from mkdocs.plugins import event_priority

MARKER = "<!-- proof-terminal -->"

#: The marker expands only where it stands alone at column 0.  An indented
#: copy is left as text, which is what lets the style page's fenced source
#: example *show* the marker without summoning a terminal into a code block.
MARKER_LINE = re.compile(r"(?m)^<!-- proof-terminal -->$")

#: Relative to docs_dir.  Committed, and regenerated by `make proof`.
DATA = "assets/proof.json"

#: Operator words, coloured `ow` when they stand alone between spaces --
#: pygments.lexers.AgdaLexer's reading of the same glyphs.  Brackets and
#: parentheses stay plain, as they do in the 404's goal block.
OPERATORS = {":", "=", "→", "∀", "λ", ","}

#: Split into atoms: runs of whitespace, brackets and parentheses are
#: boundaries; everything between them is a candidate token.
ATOMS = re.compile(r"(\s+|[()\[\]])")


def _load(config):
    path = Path(config["docs_dir"]) / DATA
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise PluginError(f"{MARKER} needs {DATA}; run `make proof`.")
    for key in ("source", "agda", "lines", "hole", "goals", "fill", "names",
                "check"):
        if key not in data:
            raise PluginError(f"{DATA} has no `{key}`; regenerate it.")
    return data


def _code(line: str, names: set[str]) -> str:
    """One line of Agda, coloured by the rules stated above."""
    # The stripped line, not the raw one: the vignette lives inside an
    # anonymous module, so its comment lines arrive indented -- and a line
    # whose first token is `--` is wholly a comment wherever it starts.
    if line.lstrip().startswith("--"):
        return f'<span class="c1">{escape(line)}</span>'
    out = []
    for atom in ATOMS.split(line):
        if atom in names:
            out.append(f'<span class="nf">{escape(atom)}</span>')
        elif atom in OPERATORS:
            out.append(f'<span class="ow">{escape(atom)}</span>')
        else:
            out.append(escape(atom))
    return "".join(out)


def _render(data, config):
    names = set(data["names"])
    src = data["source"]
    goals = data["goals"]

    body = [f'<div class="proof-line">{_code(line, names)}</div>'
            for line in data["lines"]]

    # The filled line, in both of its recorded states: the hole as loaded
    # (hidden at rest) and the fill as given.  The hole span reuses the
    # 404's recipe by class, not by copy.
    lhs = data["hole"].rsplit(" = ", 1)[0]
    body.append(
        f'<div class="proof-line proof-hole-line" hidden>{_code(lhs, names)}'
        f' <span class="ow">=</span>'
        f' <span class="proof-hole">{{! !}}</span></div>'
    )
    body.append(
        f'<div class="proof-line proof-fill-line">'
        f'{_code(data["fill"], names)}</div>'
    )

    check, _, version = data["check"].partition(" · ")
    body.append(
        f'<div class="proof-line proof-check">{escape(check)}'
        f' <span class="proof-dim">· {escape(version)}</span></div>'
    )

    hud = " · ".join(f'?{g["id"]} : {g["type"]}' for g in goals)
    body.append(
        f'<div class="proof-hud" data-goal="{escape(hud)}">All done</div>'
    )

    blob = f'{config["repo_url"]}/blob/main/{escape(src["file"])}'
    bar = (
        f'<a class="proof-src" href="{blob}" '
        f'title="The session&#8217;s source, in this repository; '
        f'`{escape(src["command"])}` re-runs it">{escape(src["file"])}</a>'
        f'<button class="proof-replay" type="button" hidden>↻ replay</button>'
        f'<span class="proof-goals proof-goals-zero">0 goals</span>'
    )

    return (
        f'<div class="proof" role="group" data-goals-open="{len(goals)}" '
        f'aria-label="Replay of the Agda session that checks '
        f'{escape(src["file"])}">\n'
        f'<div class="proof-bar">{bar}</div>\n'
        f'<div class="proof-body">\n' + "\n".join(body) + "\n</div>\n</div>"
    )


@event_priority(-100)
def on_page_markdown(markdown, *, page, config, files):
    if not MARKER_LINE.search(markdown):
        return None
    html = _render(_load(config), config)
    return MARKER_LINE.sub(lambda _: html, markdown)
