"""Expand `<!-- proof-terminal -->` into the typed-proof terminal (M3-2d).

The terminal replays the hole-filling sessions recorded in
`docs/assets/proof.json` (regenerated by `make proof`, which drives a real
Agda over the five modules in `agda/`), one session per tab.  This hook
renders every session's *final* state -- every line coloured, the goal count
at zero, the `✓` line with the version Agda reported -- so a crawler, a
JS-off reader and a reduced-motion reader all see completed proofs with
nothing missing.  `proof.js` only rewinds that state and types it back in
(ADR-009: the animation is a way of arriving at the truth, never the only
carrier of it).

## One renderer

Same reasoning as `evidence_hook.py`: the markup carries the session data
(the hole line and the goal live in it, for the replay), and hand-writing
that into a page is how a displayed goal and a recorded one drift apart.
The JSON holds facts only; the colouring below is presentation, and it
follows `overrides/404.html`'s precedent -- Pygments' Agda vocabulary (`nf`
for a defined name, `ow` for an operator word, `c1` for a comment), so the
terminal is coloured with the same classes, off the same tokens, as every
real code block on the site.  Only identifiers a transcript lists in
`names` are coloured as definitions: the renderer never guesses at what is
a name.  Tab labels are the transcripts' `label` fields -- the definienda
themselves -- so the tab bar never invents a name either.

## The replay's contract with this markup

`proof.js` finds, inside `.proof`: `.proof-tabs`, the tablist, shipped
`hidden` (without the script the buttons would switch nothing, and a
control that does nothing should not exist); and one `.proof-panel` per
session, all but the first shipped `hidden`.  Inside each panel:
`.proof-line` elements in session order, of which one is the hidden
`.proof-hole-line` (the hole state of the line that gets filled) and its
successor `.proof-fill-line` (the final state); inside the hole span, an
empty `.proof-hole-body` the replay types the fill into, Emacs-style,
before the brackets vanish; `.proof-check`, revealed last, not typed -- the
compiler speaks, the visitor does not type its output; `.proof-hud`, whose
`data-goal` is the recorded goal and whose resting text is the all-done
state; `.proof-goals`, the goal pill, with the open count in the panel's
`data-goals-open`; and `.proof-replay`, shipped `hidden` for the same
reason the tablist is.  Element ids (`proof-tab-N`/`proof-panel-N`) wire
the ARIA tab pattern and so assume at most one terminal per page.
"""

from __future__ import annotations

import json
import re
from html import escape
from pathlib import Path

from mkdocs.exceptions import PluginError
from mkdocs.plugins import event_priority

MARKER = "<!-- proof-terminal -->"

#: The marker expands only where it stands alone at column 0.  An indented
#: copy is left as text, which is what lets the style page's fenced source
#: example *show* the marker without summoning a terminal into a code block.
MARKER_LINE = re.compile(r"(?m)^<!-- proof-terminal -->$")

#: Relative to docs_dir.  Committed, and regenerated by `make proof`.
DATA = "assets/proof.json"

#: Operator words, coloured `ow` when they stand alone between spaces --
#: pygments.lexers.AgdaLexer's reading of the same glyphs.  Brackets and
#: parentheses stay plain, as they do in the 404's goal block.
OPERATORS = {":", "=", "→", "∀", "λ", ",", "≡", "≤", "∧", "∨", "¬"}

#: Split into atoms: runs of whitespace, brackets and parentheses are
#: boundaries; everything between them is a candidate token.
ATOMS = re.compile(r"(\s+|[()\[\]])")


def _load(config):
    path = Path(config["docs_dir"]) / DATA
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise PluginError(f"{MARKER} needs {DATA}; run `make proof`.")
    for key in ("agda", "sessions"):
        if key not in data:
            raise PluginError(f"{DATA} has no `{key}`; regenerate it.")
    if not data["sessions"]:
        raise PluginError(f"{DATA} lists no sessions; regenerate it.")
    for sess in data["sessions"]:
        for key in ("label", "source", "lines", "hole", "goals", "fill",
                    "names", "check"):
            if key not in sess:
                raise PluginError(
                    f"a session in {DATA} has no `{key}`; regenerate it.")
    return data


def _code(line: str, names: set[str]) -> str:
    """One line of Agda, coloured by the rules stated above."""
    # The stripped line, not the raw one: a replay block may live inside an
    # anonymous module, so its comment lines can arrive indented -- and a
    # line whose first token is `--` is wholly a comment wherever it starts.
    if line.lstrip().startswith("--"):
        return f'<span class="c1">{escape(line)}</span>'
    out = []
    for atom in ATOMS.split(line):
        if atom in names:
            out.append(f'<span class="nf">{escape(atom)}</span>')
        elif atom in OPERATORS:
            out.append(f'<span class="ow">{escape(atom)}</span>')
        else:
            out.append(escape(atom))
    return "".join(out)


def _panel(i: int, sess: dict, config) -> str:
    """One session's tabpanel: bar, lines, hole/fill pair, ✓ line, HUD."""
    names = set(sess["names"])
    src = sess["source"]
    goals = sess["goals"]

    body = [f'<div class="proof-line">{_code(line, names)}</div>'
            for line in sess["lines"]]

    # The filled line, in both of its recorded states: the hole as loaded
    # (hidden at rest) and the fill as given.  The hole span reuses the
    # 404's recipe by class, not by copy; the empty body span inside it is
    # where the replay types the fill before the brackets vanish.
    lhs = sess["hole"].rsplit(" = ", 1)[0]
    body.append(
        f'<div class="proof-line proof-hole-line" hidden>{_code(lhs, names)}'
        f' <span class="ow">=</span>'
        f' <span class="proof-hole">{{!<span class="proof-hole-body">'
        f'</span> !}}</span></div>'
    )
    body.append(
        f'<div class="proof-line proof-fill-line">'
        f'{_code(sess["fill"], names)}</div>'
    )

    check, _, version = sess["check"].partition(" · ")
    body.append(
        f'<div class="proof-line proof-check">{escape(check)}'
        f' <span class="proof-dim">· {escape(version)}</span></div>'
    )

    hud = " · ".join(f'?{g["id"]} : {g["type"]}' for g in goals)
    body.append(
        f'<div class="proof-hud" data-goal="{escape(hud)}">All done</div>'
    )

    blob = f'{config["repo_url"]}/blob/main/{escape(src["file"])}'
    bar = (
        f'<a class="proof-src" href="{blob}" '
        f'title="The session&#8217;s source, in this repository; '
        f'`{escape(src["command"])}` re-runs it">{escape(src["file"])}</a>'
        f'<button class="proof-replay" type="button" hidden>↻ replay</button>'
        f'<span class="proof-goals proof-goals-zero">0 goals</span>'
    )

    hidden = "" if i == 0 else " hidden"
    return (
        f'<div class="proof-panel" role="tabpanel" id="proof-panel-{i}" '
        f'aria-labelledby="proof-tab-{i}" data-goals-open="{len(goals)}"'
        f'{hidden}>\n'
        f'<div class="proof-bar">{bar}</div>\n'
        f'<div class="proof-body">\n' + "\n".join(body) + "\n</div>\n</div>"
    )


def _render(data, config):
    tabs = "".join(
        f'<button class="proof-tab" role="tab" id="proof-tab-{i}" '
        f'aria-controls="proof-panel-{i}" '
        f'aria-selected="{"true" if i == 0 else "false"}"'
        f'{"" if i == 0 else " tabindex=\"-1\""}>'
        f'{escape(sess["label"])}</button>'
        for i, sess in enumerate(data["sessions"])
    )
    panels = "\n".join(_panel(i, sess, config)
                       for i, sess in enumerate(data["sessions"]))
    return (
        f'<div class="proof" role="group" aria-label="Replays of the Agda '
        f'sessions that check the lemmas in this repository&#8217;s agda/ '
        f'directory">\n'
        f'<div class="proof-tabs" role="tablist" aria-label="Lemmas" hidden>'
        f'{tabs}</div>\n'
        f'{panels}\n</div>'
    )


@event_priority(-100)
def on_page_markdown(markdown, *, page, config, files):
    if not MARKER_LINE.search(markdown):
        return None
    html = _render(_load(config), config)
    return MARKER_LINE.sub(lambda _: html, markdown)
